package com.thane98.exalt.model

enum class TokenType {
    // Delimiters
    LBRACKET, RBRACKET, LPAREN, RPAREN, LBRACE, RBRACE,
    COMMA, AMPERSAND, SEMICOLON, EOF, ARROW, AT_SIGN,

    // Basic Operators
    PLUS, FPLUS, MINUS, FMINUS, TIMES, FTIMES, DIVIDE, FDIVIDE,
    MODULO, EQ, FEQ, NE, FNE, LT, FLT, GT, FGT, LE, FLE, GE, FGE,
    RIGHT_SHIFT, LEFT_SHIFT, BINARY_NOT, LOGICAL_NOT, BINARY_OR,
    LOGICAL_AND, LOGICAL_OR, XOR, INCREMENT, DECREMENT,

    // Asignment Operators
    ASSIGN, ASSIGN_ADD, ASSIGN_FLOAT_ADD, ASSIGN_SUBTRACT,
    ASSIGN_FLOAT_SUBTRACT, ASSIGN_MULTIPLY, ASSIGN_FLOAT_MULTIPLY,
    ASSIGN_DIVIDE, ASSIGN_FLOAT_DIVIDE, ASSIGN_MODULO,
    ASSIGN_BINARY_OR, ASSIGN_BINARY_AND, ASSIGN_XOR,
    ASSIGN_LEFT_SHIFT, ASSIGN_RIGHT_SHIFT,

    // Misc. Operators
    FRAME_REF, GLOBAL_FRAME_REF,

    // Keywords
    SCRIPT, EVENT, FUNC, VAR, FOR, WHILE, IF, ELSE,
    MATCH, RETURN, YIELD, ARRAY, GOTO, LABEL,

    // Other
    IDENTIFIER, INT, FLOAT, STRING,
}